### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by actionxboy** [Sigton/stealth#3] opened 2017-03-02 22:10 UTC
Hi! I saw Stealth on Scratch first, then followed the link in the description to here. I downloaded the game and played it, and it is absolutely amazing! In my 5 minutes of playing just now, I've experienced a couple of bugs.

1: On one of the levels (I don't know which one), a tip says to try going over the guard. There is not a guard there that you have to go over. I'm not sure if that's talking about the one on the platform a couple of landings above or if he is missing, so I included it just in case.

2: Getting caught while crouching respawns you as forever hovering in the air and crouching, meaning you can jump in this stage. Crouching during that seems to fix it, though. 

3: Turning in the air (falling off a platform and trying to move) makes you stay still until you press a different button (I'm not 100% sure if that is a bug or not).

4: Final and worst bug. Remember earlier how I talked about being spawned as a hovering crouched person? If you get caught by a guard in that stage, the game instantly crashes.

Besides those bugs, this game is really awesome 👍  I'll be happy to see this game developing even more than it already is 🤞 Great job!

EDIT: Found out that dying or being caught in the crouch form will make you be stuck as that, but but it won't crash when you die by acid again.

**Comment by Sigton** [comment] 2017-03-05 20:13
1. Yeah I removed that guard to improve performance but forgot to remove the text.
2. Ah interesting, I'll take a look at that one.
3. I've known about this bug, but haven't got round to fixing it yet.
4. Okay I'll definitely try fix that. I have a sneaking suspicion about what may be causing it.

Thanks for finding these bugs, and I'm glad you enjoyed the game :)

Sigton

**Comment by actionxboy** [comment] 2017-03-05 20:23
No problem :P It's really fun :D

**Comment by Sigton** [comment] 2017-03-05 20:41
Thanks :D

Sigton

**Comment by actionxboy** [comment] 2017-03-18 00:00
Not sure what happened with the updates, but an error message popped up in CMD (which is good because it happened in the crouching crash glitch)
I'm not sure what the error means but I'll try to take a look at it via notepad ++

The error message:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
  File "source/main.py", line 77, in launch
  File "source/main.py", line 114, in run
  File "C:\Users\Tanya\Desktop\Stealth Testing\3-17-2017\stealth-master\stealth-master\build\exe.win-amd64-3.4\menu.py", line 140, in run
    button.command()
  File "C:\Users\Tanya\Desktop\Stealth Testing\3-17-2017\stealth-master\stealth-master\build\exe.win-amd64-3.4\menu.py", line 77, in <lambda>
    320, 350, lambda: self.game.run())
  File "C:\Users\Tanya\Desktop\Stealth Testing\3-17-2017\stealth-master\stealth-master\build\exe.win-amd64-3.4\game.py", line 242, in run
    if funcs.pixel_perfect_collision(player, hit):
  File "C:\Users\Tanya\Desktop\Stealth Testing\3-17-2017\stealth-master\stealth-master\build\exe.win-amd64-3.4\funcs.py", line 35, in pixel_perfect_collision
    if mask1[y1+y][x1+x] != 0 and mask2[y2+y][x2+x] != 0:
IndexError: list index out of range

**Comment by Sigton** [comment] 2017-03-25 12:17
Ah I see what the problem is. Because crouching and running have two different hitboxes, I need to switch between them when you start/stop crouching. I think the function call to stop crouching can be bypassed when you die, but it also sets it so you're not crouching? Not entirely sure but it should be easy enough to fix. Thanks again :)

**Comment by Sigton** [comment] 2017-03-26 07:57
Since all these bugs are fixed now, I'll close this. Thanks again for your help!

**Closed as completed by Sigton** 2017-03-26 07:57 UTC
